apiVersion: v1
kind: Pod
metadata: 
  name: fortune2s
spec:
  containers:
  - image: luksa/fortune:args
    env:
    - name: INTERVAL
      valueFrom:
        #Grabs the config map value as usual
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval
    #Injects the config map value into the command line argument 
    args: ["$(INTERVAL)"] 
