apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-shared-storage-claim
  labels:
    app: nextcloud
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Ti