apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice-server
  labels:
    app: onlyoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: onlyoffice-server
  template:
    metadata:
      labels:
        app: onlyoffice
        pod-label: onlyoffice-server
    spec:
      containers: 
      - name: onlyoffice
        image: alehoho/oo-ce-docker-license
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-nodeport
  labels:
    app: onlyoffice
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30125
  selector:
    pod-label: onlyoffice-server

