apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-claim
  labels:
    app: nextcloud
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-db
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: nextcloud-db-pod
  template:
    metadata:
      labels:
        pod-label: nextcloud-db-pod
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: nextcloud
        envFrom:
        - secretRef: 
            name: nextcloud-db-secret
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
          subPath: mysql-data
      volumes:
      - name: db-storage 
        persistentVolumeClaim:
          claimName: nextcloud-db-claim

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db
  labels:
    app: nextcloud
spec:
  selector:
    pod-label: nextcloud-db-pod
  ports:
  - protocol: TCP
    port: 5432
