apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 10Gi #Politely asks for this much storage 
  accessModes: #Want it to only support one person reading/writing (Make sure this
  #aligns with the permissions of the PV)
  - ReadWriteOnce
  storageClassName: "" #Something Something dynamic Provisioning 
    